repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
            args: ["--markdown-linebreak-ext=md"]
          - id: check-ast
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.7.0
      hooks:
          - id: mypy
            args: [--ignore-missing-imports]
            additional_dependencies: [types-redis]
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            name: isort (python)
    - repo: https://github.com/psf/black
      rev: 23.11.0
      hooks:
          - id: black
    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.18.0
      hooks:
          - id: gitlint
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.1.5
      hooks:
          - id: ruff
            args: ["--ignore", "E501", "--per-file-ignores", "__init__.py:F401"]
