repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-yaml
            exclude: mkdocs.yml
          - id: end-of-file-fixer
          - id: trailing-whitespace
            args: ["--markdown-linebreak-ext=md"]
          - id: check-ast
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.991
      hooks:
          - id: mypy
            args: [--ignore-missing-imports]
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            name: isort (python)
    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
          - id: black
    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.17.0 # Fill in a tag / sha here
      hooks:
          - id: gitlint
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.0.118
      hooks:
          - id: ruff
            args:
                [
                    "--ignore=E203,W503,E501",
                    "--per-file-ignores=__init__.py:F401",
                ]
