[tool.poetry]
name = "pyle38"
version = "0.1.0"
description = "Async python client for Tile38"
authors = ["Benjamin Ramser <legionaerr@googlemail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
aioredis = "^1.3.1"
pydantic = "^1.8.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pre-commit = "^2.11.1"
mypy = "^0.812"
black = "^20.8b1"
pytest-asyncio = "^0.14.0"
gitlint = "^0.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
